import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  out: './drizzle',
  schema: [
    './src/db/actividadUsuarioSchema.ts',
    './src/db/asistenciasUsuarioSchema.ts',
    './src/db/conversacionesSchema.ts',
    './src/db/eventosSchema.ts',
    './src/db/forosSchema.ts',
    './src/db/mensajesSchema.ts',
    './src/db/oportunidadesSchema.ts',
    './src/db/rolesProyectoSchema.ts',
    './src/db/rolesUsuarioSchema.ts',
    './src/db/tagsSchema.ts',
    './src/db/universidadesSchema.ts',
    './src/db/asistenciasEventoSchema.ts',
    './src/db/bloquesSchema.ts',
    './src/db/experienciaUsuarioSchema.ts',
    './src/db/hilosSchema.ts',
    './src/db/ofertasLaboralesSchema.ts',
    './src/db/participacionesProyectoSchema.ts',
    './src/db/perfilesSchema.ts',
    './src/db/postulacionesLaboralesSchema.ts',
    './src/db/postulacionesSchema.ts',
    './src/db/proyectosSchema.ts',
    './src/db/proyectosValidacionesSchema.ts',
    './src/db/relacionesBloquesSchema.ts',
    './src/db/reportesSchema.ts',
    './src/db/respuestasHiloSchema.ts',
    './src/db/seguimientosSchema.ts',
    './src/db/taggablesSchema.ts',
    './src/db/tokensInicialesAccesoSchema.ts',
    './src/db/versionesBloquesSchema.ts',
    './src/db/usuariosSchema.ts',
  ],
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  verbose: true,
  strict: true,
});